[workspace]
members = ["xtask"]

[package]
name = "guitar_pitch_shifter_plugin"
version = "0.1.0"
edition = "2021"
authors = ["Transpose Plugin"]
license = "UNLICENSED"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git" }

[dev-dependencies]
hound = "3.5"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
